In [18]:
import numpy as np

In [19]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [20]:
type(a)

numpy.ndarray

In [21]:
a.ndim

1

In [22]:
a.size

4

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]]);
print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
arr.ndim

2

In [25]:
arr.size

6

In [26]:
arr.shape

(2, 3)

In [27]:
arr.dtype

dtype('int32')

In [28]:
ar = np.array([[1, 'a', "world"], [3, 4, 5]])

In [29]:
ar.dtype

dtype('<U11')

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a

array([1, 2, 3, 4])

In [32]:
ar

array([['1', 'a', 'world'],
       ['3', '4', '5']], dtype='<U11')